- hosts: olympus_local
  tasks:
    - ansible.builtin.shell:
        chdir: /root
        cmd: touch great-success.txt

- hosts: olympus_local
  module_defaults:
    group/community.proxmox.proxmox:
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_user }}"
      api_token_id: "{{ proxmox_token_id }}"
      api_token_secret: "{{ proxmox_api_key }}"
  roles:
    - hypervisor

