- name: Create ZFS dataset to hold VM templates
  community.general.zfs:
    name: main-storage/vm-templates
    state: present

- name: Create folder storage for VM templates
  community.proxmox.proxmox_storage:
    nodes:
      - olympus
    name: vm-templates
    type: dir
    content:
      - vztmpl
    dir_options:
      path: /main-storage/vm-templates

- name: Fetch fedora image into storage
  community.proxmox.proxmox_template:
    node: olympus
    storage: vm-templates
    template: ubuntu-26.04-standard_26.04-1_amd64.tar.zst

- name: Add WakeMeOps repository
  ansible.builtin.deb822_repository:
    name: wakemeops
    types: deb
    enabled: true
    architectures: amd64
    components:
      - dev
      - devops
      - secops
      - terminal
      - desktop
    suites: stable
    uris: http://deb.wakemeops.com/wakemeops/
    signed_by: "{{ lookup('file', 'wakemeops_pgp.txt') }}"

- name: Install apt packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - rclone
      - resticprofile

- name: Create directory for restic config
  ansible.builtin.file:
    path: /opt/backup
    state: directory
    
- name: Copy restic backup configuration
  ansible.builtin.copy:
    src: profiles.toml
    dest: /opt/backup/profiles.toml
    owner: root
    group: root

- name: Initialize restic if it hasn't been initialized already
  ansible.builtin.shell:
    creates: /opt/backup/.restic_initialized
    chdir: /opt/backup/
    cmd: resticprofile init && touch .restic_initialized

- name: Enable scheduled backups
  ansible.builtin.shell:
    creates: /opt/backup/.restic_scheduled
    chdir: /opt/backup
    cmd: resticprofile schedule && touch .restic_scheduled
