- name: Create ZFS dataset to hold VM templates
  community.general.zfs:
    name: main-storage/vm-templates
    state: present

- name: Create folder storage for VM templates
  community.proxmox.proxmox_storage:
    nodes:
      - olympus
    name: vm-templates
    type: dir
    content:
      - vztmpl
    dir_options:
      path: /main-storage/vm-templates

- name: Fetch fedora image into storage
  community.proxmox.proxmox_template:
    node: olympus
    storage: vm-templates
    template: ubuntu-26.04-standard_26.04-1_amd64.tar.zst

- name: Add WakeMeOps repository
  ansible.builtin.deb822_repository:
    name: wakemeops
    types: deb
    enabled: true
    architectures: amd64
    components:
      - dev
      - devops
      - secops
      - terminal
      - desktop
    suites: stable
    uris: http://deb.wakemeops.com/wakemeops/
    signed_by: "{{ lookup('file', 'wakemeops_pgp.txt') }}"

- name: Install apt packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - rclone

