- name: Install ansible
  ansible.builtin.apt:
    update_cache: true
    name: ansible

- name: Populate password file
  ansible.builtin.copy:
    src: ~/.ansible-pass
    dest: /root/.ansible-pass
    owner: root
    group: root
    mode: '0600'
