- name: Install necessary packages
  ansible.builtin.apt:
    update_cache: true
    name: 
      - ansible
      - git

- name: Populate password file
  ansible.builtin.copy:
    src: ~/.ansible-pass
    dest: /root/.ansible-pass
    owner: root
    group: root
    mode: '0600'

- name: Clone this repo to hypervisor
  ansible.builtin.git:
    repo: "https://github.com/emanguy/olympus-management.git"
    dest: /var/ansible
    version: main

- name: Set up cron job to auto-run ansible jobs
  ansible.builtin.include_role:
    name: systemd_template
    tasks_from: cron_unit
  vars:
    cron_name: ansible-config-pull
    cron_description: Regularly pull ansible configuration from github and apply
    cron_command: /bin/bash -c "git pull && ansible-playbook configure_olympus.yml"
    cron_workdir: /var/ansible
    cron_schedule: "*:0/10"
