version = "1"
global.scheduler = "systemd"

[default]
repository = "rclone:proton-drive:Olympus-Backup"
password-file = "/root/.server-backup-pass"
compression = "max"

[default.backup]
verbose = true
source = [ 
  # Immich raw images and videos
  "/main-storage/subvol-103-disk-1/upload",
  # Nextcloud documents & user data
  "/main-storage/subvol-109-disk-1/data"
]
tag = "scheduled"

schedule = "Sun,Tue,Thu,Sat 01:00"
schedule-permission = "user"

iexclude = [
  "*.log",
  "*.log.*",
  "*.html"
]

[default.forget]
prune = true
keep-daily = 14
keep-monthly = 12
tag = "scheduled"

schedule = "Mon,Wed,Fri 01:00"
schedule-permission = "user"
